/* OC SWITRTS Data Codebook */
/* Version 1.0, Date: 2024-11-20 */


// Defining local variables
local dver "1.0"
local date "2024-11-20"
local myday = "`c(current_date)`"



clear all

// Label the dataset
label data "OC SWITRTS Stata Dataset version " + string(`dver') + " (" + "`date'" + ")"

// Label Variables in dataset
label var objectid "Object ID"
label var globalid "Global ID"
label var guid "GUID Related Table Identifier"
label var case_id "Case ID"
label var cid "Crash ID"
label var pid "Party ID"
label var vid "Victim ID"
label var party_number "Party Number"
label var victim_number "Victim Number"
label var crashes_indicator "Crashes Binary Indicator"
label var parties_indicator "Parties Binary Indicator"
label var victims_indicator "Victims Binary Indicator"
label var city "City"
label var city_name "City Name"
label var place_type "Place Type"
label var collision_datetime "Crash Date and Time"
label var collision_date "Crash Date"
label var collision_time "Crash Time"
label var accident_year "Crash Year"
label var collision_month "Crash Month"
label var day_of_week "Day of Week"
label var proc_date "Processing Date"
label var collision_time_intervals "Crash Time Intervals"
label var collision_time_rush_hours "Rush Hours"
label var collision_severity "Crash Severity"
label var collision_severity_binary "Crash Severity (binary)"
label var collision_severity_reclass "Crash Severity Reclassified"
label var collision_severity_ranked "Crash Severity Ranked"
label var party_count "Party Count"
label var victim_count "Victim Count"
label var number_killed "Killed Victims"
label var number_injured "Injured Victims"
label var count_severe_inj "Severe Injury Count"
label var count_visible_inj "Other Visible Injury Count"
label var count_complaint_pain "Complaint of Pain Injury Count"
label var count_ped_killed "Pedestrian Killed Count"
label var count_ped_injured "Pedestrian Injured Count"
label var count_bicyclist_killed "Bicyclists Killed Count"
label var count_bicyclist_injured "Bicyclists Injured Count"
label var count_mc_killed "Motorcyclist Killed Count"
label var count_mc_injured "Motorcyclist Injured Count"
label var primary_coll_factor "Primary Crash Factor"
label var type_of_collision "Type of Crash"
label var pedestrian_accident "Pedestrian Crash"
label var bicycle_accident "Bicycle Crash"
label var motorcycle_accident "Motorcycle Crash"
label var truck_accident "Truck Crash"
label var hit_and_run "Hit and Run"
label var alcohol_involved "Alcohol Inovlved"
label var juris "Jurisdiction"
label var officer_id "Officer ID"
label var reporting_district "Reporting District"
label var chp_shift "CHP Shift"
label var cnty_city_loc "County City Location"
label var special_cond "Special Condition"
label var beat_type "Beat Type"
label var chp_beat_type "CHP Beat Type"
label var chp_beat_class "CHP Beat Class"
label var beat_number "Beat Number"
label var primary_rd "Primary Road"
label var secondary_rd "Secondary Road"
label var distance "Distance"
label var direction "Direction"
label var intersection "Intersection"
label var weather_1 "Weather 1"
label var weather_2 "Weather 2"
label var weather_combined "Combined Weather Conditions"
label var road_surface "Road Surface"
label var road_cond_1 "Road Condition 1"
label var road_cond_2 "Road Condition 2"
label var lighting "Lighting"
label var control_device "Control Device"
label var state_hwy_ind "State Highway Indicator"
label var side_of_hwy "Side of Highway"
label var tow_away "Tow Away"
label var pcf_code_of_viol "PCF Violation Code"
label var pcf_viol_category "PCF Violation Category"
label var pcf_violation "PCF Violation"
label var pcf_viol_subsection "PCF Violation Subsection"
label var mviw "Motor Vehicle Involved With"
label var ped_action "Ped Action"
label var not_private_property "Not Private Property"
label var stwd_vehtype_at_fault "Statewide Vehicle Type at Fault"
label var chp_vehtype_at_fault "CHP Vehicle Type at Fault"
label var primary_ramp "Primary Ramp"
label var secondary_ramp "Secondary Ramp"
label var party_type "Party Type"
label var at_fault "At Fault"
label var party_sex "Party Sex"
label var party_age "Party Age"
label var race "Party Race"
label var party_number_killed "Party Number Killed"
label var party_number_injured "Party Number Injured"
label var inattention "Inattention"
label var party_sobriety "Party Sobriety"
label var party_drug_physical "Party Drug Physical"
label var dir_of_travel "Direction of Travel"
label var party_safety_equip_1 "Party Safety Equipment 1"
label var party_safety_equip_2 "Party Safety Equipment 2"
label var finan_respons "Financial Responsibility"
label var sp_info_1 "Special Information 1"
label var sp_info_2 "Special Information 2"
label var sp_info_3 "Special Information 3"
label var oaf_violation_code "OAF Violation Code"
label var oaf_viol_cat "OAF Violation Category"
label var oaf_viol_section "OAF Violation Section"
label var oaf_violation_suffix "OAF Violation Suffix"
label var oaf_1 "Other Associated Factor 1"
label var oaf_2 "Other Associated Factor 2"
label var move_pre_acc "Movement Preceding Crash"
label var vehicle_year "Vehicle Year"
label var vehicle_make "Vehicle Make"
label var stwd_vehicle_type "Statewide Vehicle Type"
label var chp_veh_type_towing "CHP Vehicle Type Towing"
label var chp_veh_type_towed "CHP Vehicle Type Towed"
label var special_info_f "Special Info F"
label var special_info_g "Special Info G"
label var victim_role "Victim Role"
label var victim_sex "Victim Sex"
label var victim_age "Victim Age"
label var victim_degree_of_injury "Victim Degree of Injury"
label var victim_degree_of_injury_binary "Victim Degree of Injury (binary)"
label var victim_seating_position "Victim Seating Position"
label var victim_safety_equip_1 "Victim Safety Equipment 1"
label var victim_safety_equip_2 "Victim Safety Equipment 2"
label var victim_ejected "Victim Ejected"
label var city_area_sqmi "City Area (sq. miles)"
label var city_popdens "City Population Density (per sq. mi)"
label var city_hudens "City Housing Density (per sq. mi)"
label var city_popt "City Total Population"
label var city_hut "City Total Housing Units"
label var city_popa "City Asian Population"
label var city_popb "City Black Population"
label var city_poph "City Hispanic Population"
label var city_popw "City White Population"
label var city_vehicles "City Aggregate Number of Vehicles Commutting"
label var city_travel_time "City Aggregate Travel Time to Work (min)"
label var rid "Road ID"
label var rname "Road Name"
label var rcat "Road Category"
label var rlength "Road Length"
label var latitude "GPS Latitude"
label var longitude "GPS Longitude"
label var point_x "X Coordinate Location"
label var point_y "Y Coordinate Location"


// Add variable notes in dataset
notes objectid : "ESRI Object ID"
notes globalid : "ESRI Global ID string identifier"
notes guid : "ESRI GUID to be used in merging related tables"
notes case_id : "Unique identifier of the crash case"
notes cid : "Unique identifier of the crash case"
notes pid : "Unique identifier for the party case"
notes vid : "Unique identifier of the victim case"
notes party_number : "A number that together with the CASE_ID uniquely identifies a party in a crash"
notes victim_number : "The unique identifier of the victim"
notes crashes_indicator : "Binary flag, 1 if the record is a crash, 0 if not"
notes parties_indicator : "Binary flag, 1 if the record is a party, 0 if not"
notes victims_indicator : "Binary flag, 1 if the record is a victim, 0 if not"
notes city : "Reported City of the crash"
notes city_name : "City name from locational query"
notes place_type : "City or Unincorporated Area"
notes collision_datetime : "Full date and time string of the crash"
notes collision_date : "The date when the crash occurred"
notes collision_time : "The time when the crash occurred in 24h format"
notes accident_year : "The year when the crash occurred"
notes collision_month : "Month number from crash date"
notes day_of_week : "Code for the day of the week when the crash occurred"
notes proc_date : "The date that the crash case was last changed"
notes collision_time_intervals : "Crash time interval ranges classification"
notes collision_time_rush_hours : "Rush hours interval ranges (Mon-Fri mornings and evenings)"
notes collision_severity : "The worst injury suffered by any victim in the crash"
notes collision_severity_binary : "Binary classification of the worst injury suffered by any victim in the crash"
notes collision_severity_reclass : "Reclassified crash severity based on the worst injury suffered by any victim in the crash"
notes collision_severity_ranked : "Ranked crash severity based on the worst injury suffered by any victim in the crash"
notes party_count : "Number of parties involved in the crash"
notes victim_count : "Number of victims involved in each party"
notes number_killed : "Number of killed victims"
notes number_injured : "Number of injured victims"
notes count_severe_inj : "Number of victims in the crash with suspected serous injury or severe injury"
notes count_visible_inj : "Number of victims in the crash with suspected minor injury or visible injury"
notes count_complaint_pain : "Number of victims in the crash with possible injury or complaint of pain"
notes count_ped_killed : "Number of killed pedestrian victims"
notes count_ped_injured : "Number of injured pedestrian victims"
notes count_bicyclist_killed : "Number of killed bicyclists"
notes count_bicyclist_injured : "Number of injured bicyclists"
notes count_mc_killed : "Number of killed motorcyclists"
notes count_mc_injured : "Number of injured motorcyclists"
notes primary_coll_factor : "The primary cause of the crash"
notes type_of_collision : "The general type of crash as determined by the first injury or damage-causing event"
notes pedestrian_accident : "Indicates whether the crash involved a pedestrian"
notes bicycle_accident : "Indicates whether the crash involved a bicycle"
notes motorcycle_accident : "Indicates whether the crash involved a motorcycle"
notes truck_accident : "Indicates whether the crash involved a big truck"
notes hit_and_run : "A flag to indicate the severity of hit-and-run crash. Felony hit-and-run resulted in injury or death to other parties. Misdemeanor hit-and-run did not result in injury or death to other parties"
notes alcohol_involved : "Indicates whether the crash involved a party that had been drinking. Note - a passenger does not count as a party"
notes juris : "Law enforcement agency that has jurisdiction over the crash"
notes officer_id : "The badge number of the officer who wrote the crash report"
notes reporting_district : "Reporting District on the crash report"
notes chp_shift : "CHP shift at the time of the crash"
notes cnty_city_loc : "The city or unincorporated county where the crash occurred"
notes special_cond : "A computed value. O means not private property"
notes beat_type : "Location of crash based on beat"
notes chp_beat_type : "Location of crash based on beat"
notes chp_beat_class : "Location of crash based on beat"
notes beat_number : "Beat of the officer who reported the crash"
notes primary_rd : "The name of the roadway on which the crash occurred"
notes secondary_rd : "The name of the roadway that intersects the primary roadway"
notes distance : "Distance of the crash from the intersection with the secondary roadway in ft"
notes direction : "Direction of the crash from the intersection with the secondary roadway"
notes intersection : "A flag that denotes if the crash occurred at the intersection with the secondary roadway"
notes weather_1 : "Weather condition at the time of the crash"
notes weather_2 : "Additional weather condition at the time of the crash"
notes weather_combined : "Combined Weather Conditions from WEATHER_1 and WEATHER_2 fields in numeric codes by weather conditions severity"
notes road_surface : "Roadway surface condition at the time of the crash in the traffic lane(s) involved"
notes road_cond_1 : "Roadway condition at the time of the crash in the traffic lane(s) involved"
notes road_cond_2 : "Second roadway condition at the time of the crash in the traffic lane(s) involved"
notes lighting : "Lighting conditions at the crash location and the time of the crash"
notes control_device : "Presence and condition of crash related traffic control devices at the time of the crash. Control devices include regulatory, warning, and construction sings. This excludes striping and officers or other persons directing traffic"
notes state_hwy_ind : "A flag to indicate whether the crash is on or near a state highway"
notes side_of_hwy : "Code provided by Caltrans Coders, applies to divided highway, based on nominal direction of route, for single vehicle is same as nominal direction of travel, overruled by impact with second vehicle after crossing median"
notes tow_away : "A flag to indicate whether the vehicle was towed away from the crash scene"
notes pcf_code_of_viol : "The law code that was violated and was the primary cause of the crash"
notes pcf_viol_category : "A value computed from the law section that was given as the primary cause of the crash"
notes pcf_violation : "The law section given as the primary cause of the crash. The subsection is in the data element pcf_viol_subsection"
notes pcf_viol_subsection : "The subsection of the law section given as the primary cause of the crash in the data element pcf_violation"
notes mviw : "Describes what, in conjunction with a motor vehicle in-transport, produced the first injury or damage-causing event, on or off the road"
notes ped_action : "The action just prior to the crash of the first pedestrian injured or otherwise involved"
notes not_private_property : "Y indicates that the crash did not occur on private property"
notes stwd_vehtype_at_fault : "Indicates the Statewide Vehicle Type of the party who is at fault"
notes chp_vehtype_at_fault : "Indicates the CHP Vehicle Type of the party whi is at fault"
notes primary_ramp : "A description of the ramp, if any, on primary roadway. This value is computed by the key operator from information on the crash report"
notes secondary_ramp : "A description of the ramp, if any, on secondary roadway. This value is computed by the key operator from information on the crash report"
notes party_type : "Involved party type"
notes at_fault : "Indicates whether the party was at fault in the crash"
notes party_sex : "The gender of the party"
notes party_age : "The age of the party at the time of the crash"
notes race : "The party's race based on the reporting officer's judgment"
notes party_number_killed : "Number of killed victims in the party"
notes party_number_injured : "Number of injured victims in the party"
notes inattention : "Type of inattention"
notes party_sobriety : "The state of sobriety of the party"
notes party_drug_physical : "The state of the party with regard to drugs and physical condition"
notes dir_of_travel : "Direction that the party was traveling at the time of the crash. The direction is the direction of the highway, not the compass direction"
notes party_safety_equip_1 : "The safety equipment of the party"
notes party_safety_equip_2 : "The safety equipment of the party"
notes finan_respons : "Financial responsibility of the party"
notes sp_info_1 : "Value A indicates that the crash involved in a vehicle known to be, or believed to be, transporting a hazardous material as defined in CVC Section 353, whether or not the crash involved a hazardous material incident"
notes sp_info_2 : "Cell Phone Information"
notes sp_info_3 : "Value E indicates that the crash involved a motor vehicle in-transport passing a stopped school bus with its red signal lamps in operation pursuant to CVC Section 22112, or reacting to, pursuant to CVC Section 22454"
notes oaf_violation_code : "Other associated factor law code violated"
notes oaf_viol_cat : "Category of the factor that contributed to the crash but was not the primary cause of the crash"
notes oaf_viol_section : "The CVC section of the secondary violation that contributed to the crash"
notes oaf_violation_suffix : "the subsection of the CVC section of the secondary violation that contributed to the crash"
notes oaf_1 : "A factor that contributed to the crash but was not the primary cause of the crash"
notes oaf_2 : "A factor that contributed to the crash but was not the primary cause of the crash"
notes move_pre_acc : "The action of the vehicle prior to the crash and before evasive action. This movement does not have to correspond with the PCF"
notes vehicle_year : "The model year of the party's vehicle"
notes vehicle_make : "The make of the party's vehicle"
notes stwd_vehicle_type : "Type of the party's vehicle according to a list called statewide vehicle type"
notes chp_veh_type_towing : "The type of the solitary vehicle or the tractor unit according to the CHP manual HPM 110.5 Chapter 3 Annex F vehicle type codes"
notes chp_veh_type_towed : "The type of the first trailer unit according to the CHP manual HPM 110.5 Chapter 3 Annex F vehicle type codes"
notes special_info_f : "The value F indicate that the party's vehicle is a 75ft motor truck combo"
notes special_info_g : "The value G indicates that the party's vehicle is a 32ft trailer combo"
notes victim_role : "The role of the victim"
notes victim_sex : "The gender of the victim"
notes victim_age : "The age of the victim at the time of the crash"
notes victim_degree_of_injury : "The severity of the injury to the victim"
notes victim_degree_of_injury_binary : "Binary classification of the severity of the injury to the victim"
notes victim_seating_position : "The seating position of the victim"
notes victim_safety_equip_1 : "The safety equipment of the victim"
notes victim_safety_equip_2 : "The safety equipment of the victim"
notes victim_ejected : "Indicates whether the victim was ejected from the vehicle"
notes city_area_sqmi : "City Area in Square Miles"
notes city_popdens : "City population density, population per square mile"
notes city_hudens : "City housing density, houses per square mile"
notes city_popt : "Total population in the city's area"
notes city_hut : "Total housing units in the city's area"
notes city_popa : "Total Asian population in the city's area"
notes city_popb : "Total Black or African American population in the city's area"
notes city_poph : "Total Hispanic population in the city's area"
notes city_popw : "Total White population in the city's area"
notes city_vehicles : "Aggregate number of vehicles used in commuting in the city's area"
notes city_travel_time : "Aggregate travel time to work (in minutes) in the city's area"
notes rid : "Road ID matching from the road's layer"
notes rname : "Road name from the OC Tiger/Lines layer"
notes rcat : "Road category from the OC Tiger/Lines layer"
notes rlength : "Road length from the OC Tiger/Lines layer"
notes latitude : "Latitude of the crash location in decimal degrees. The decimal point is included. LATITUDE and LONGITUDE are from the crash report"
notes longitude : "Longitude of the crash location in decimal degrees. The decimal point is included. There is no minus sign. The longitude is understood to be West of Meridian. LATITUDE and LONGITUDE are from the crash report"
notes point_x : "The longitude of the geocoded location, uses the World Geodetic System from 1984 (WGS84). POINT_X and POINT_Y are generated using the geociding process by UC Berkeley Safe TREC"
notes point_y : "The latitude of the geocoded location, uses the World Geodetic System from 1984 (WGS84). POINT_X and POINT_Y are generated using the geociding process by UC Berkeley Safe TREC"


// Define value labels
label define collision_month 1 "January" 2 "February" 3 "March" 4 "April" 5 "May" 6 "June" 7 "July" 8 "August" 9 "September" 10 "October" 11 "November" 12 "December"
label values collision_month collision_month

label define day_of_week 1 "Monday" 2 "Tuesday" 3 "Wednesday" 4 "Thursday" 5 "Friday" 6 "Saturday" 7 "Sunday"
label values day_of_week day_of_week

label define collision_time_intervals 1 "Night (00:00am to 06:00am)" 2 "Morning (06:00am to 12:00pm)" 3 "Afternoon (12:00pm to 06:00pm)" 4 "Evening (06:00pm to 12:00am)" 999 "Unknown Time"
label values collision_time_intervals collision_time_intervals

label define collision_time_rush_hours 1 "Morning Rush Hours" 2 "Evening Rush Hours" 999 "Non-Rush Hours" 999 "Unknown Time"
label values collision_time_rush_hours collision_time_rush_hours

label define collision_severity 0 "No injury, aka property damage only or PDO" 1 "Fatal injury" 2 "Suspected serious injury or severe injury" 3 "Suspected minor injury or visible injury" 4 "Possible injury or complaint of pain"
label values collision_severity collision_severity

label define collision_severity_binary 0 "Minor (minor injury pain, or no injury)" 1 "Severe (killed or serious injury)"
label values collision_severity_binary collision_severity_binary

label define collision_severity_reclass 0 "None" 1 "Possible injury or pain" 2 "Minor or visible injury" 3 "Serious or severe injury" 4 "Fatal injury"
label values collision_severity_reclass collision_severity_reclass

label define collision_severity_ranked 0 "None or minor injuries" 1 "Single injury (severe)" 2 "Multiple injuries (severe)" 3 "Single fatality, no injuries (fatal)" 4 "Single fatality, single injury (fatal)" 5 "Single fatality, multiple injuries (fatal)" 6 "Multiple fatalities, no injuries (fatal)" 7 "Multiple fatalities, single injury (fatal)" 8 "Multiple fatalities, multiple injuries (fatal)"
label values collision_severity_ranked collision_severity_ranked

label define primary_coll_factor 1 "Vehicle code violation" 2 "Other improper driving" 3 "Other than driver" 4 "Unknown" 5 "Fell asleep" 0 "Not stated"
label values primary_coll_factor primary_coll_factor

label define type_of_collision 1 "Head-on" 2 "Sideswipe" 3 "Rear-end" 4 "Broadside" 5 "Hit object" 6 "Overturned" 7 "Vehicle/pedestrian" 8 "Other" 0 "Not stated"
label values type_of_collision type_of_collision

label define pedestrian_accident 0 "No" 1 "Yes"
label values pedestrian_accident pedestrian_accident

label define bicycle_accident 0 "No" 1 "Yes"
label values bicycle_accident bicycle_accident

label define motorcycle_accident 0 "No" 1 "Yes"
label values motorcycle_accident motorcycle_accident

label define truck_accident 0 "No" 1 "Yes"
label values truck_accident truck_accident

label define hit_and_run 0 "Not Hit and Run" 1 "Misdemeanor" 2 "Felony"
label values hit_and_run hit_and_run

label define alcohol_involved 0 "No" 1 "Yes"
label values alcohol_involved alcohol_involved



